# Generated by Django 3.1 on 2021-11-08 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_auto_20211108_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='rate',
        ),
    ]
