# Generated by Django 3.1 on 2021-11-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_remove_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.IntegerField()),
                ('Title', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'history',
            },
        ),
    ]
